# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

C = int(input())
N = list(map(int, input().split()))
if 1<len(N)<100000 and 1<max(N)<10e9 and C==len(N):
  N.insert(0, N[C-1])
  del N[C]
  print(N)
else:
  print('no')