# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

N = int(input())
tmp = []
if 1<N<1000:
  while N>0:
    x = int(input())
    N-=1
    if x<10e5:
      tmp.append(x)
else:
  print('no')
tmp.reverse()
print(tmp)

