# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IOOI3mhE3G8MRzSdqkzEdVSYxFq_bYjY
"""

m = int(input())
n = int(input())

tmp = []
if 1<m<10e6 and 1<n<100:
  while n>0:
    x = int(input())
    if x<=m:
      n-=1
      tmp.append(x)
    else:
      print('Масса рыбака превышает допустимую')
else:
  print('Не допустимые значения')    
summa = sum(tmp)
z = summa / m
e = int(-1 * z // 1* -1)
print(e)

